### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by lukeapage** [aspnet/SignalR-Client-JS#1]
This repo has been here empty for a long time now..
- has it been abandoned?
- If not, has work started? are there any plans or estimated delivery dates?

**Comment by Eilon** [comment]
Definitely not abandoned! The SignalR JavaScript is still in the SignalR org here: https://github.com/SignalR/SignalR

One reason it hasn't moved is that there's no new client needed at this time, so the existing client works fine with the existing server.

**Comment by lukeapage** [comment]
I was brought here from the remove dependency on jquery issue - is there any timeline for a new client as described in that issue?

**Comment by abergs** [comment]
Same as @lukeapage

**Comment by Eilon** [comment]
@DamianEdwards @davidfowl to comment on removing the jQuery dependency.

**Comment by youngcm2** [comment]
+1

**Comment by oliverjanik** [comment]
+1

**Comment by Misiu** [comment]
+1 on removing dependency.
On previous issue (https://github.com/SignalR/SignalR/issues/372#issuecomment-14951079) there was idea of building adapters for other libraries that won't depend on jQuery.
I'd like to have native AngularJS support or ExtJS without need to include jQuery at all.

@DamianEdwards @davidfowl any plans to include this in roadmap?

**Comment by rajeshaz09** [comment]
Who need new versions of ASP.NET with out fully supporting old versions?

**Comment by Misiu** [comment]
Any news here?

**Comment by alexandero-brd** [comment]
Do you plan to update SignalR client? jQuery nowadays isn't "required library" and it would be great to have tiny client and also to officially support npm/bower packages.

**Comment by JimPanic** [comment]
Is this repository going to reflect the mentioned "investigation" in https://github.com/SignalR/SignalR/issues/372#issuecomment-233191541 ?

I'd rather not rewrite the SignalR js client if possible. But if you do not plan to, I will have to.

**Comment by moozzyk** [comment]
Yes. The work should be done here.

**Comment by joelday** [comment]
@JimPanic The great thing about writing your own is that 1. it can work exactly how you want and 2. you don't have to wait for anyone else to do it. Maybe everyone who is excited about it can help, too.

Unless you're really busy and have to focus on other things first. You know how it is.

**Comment by JimPanic** [comment]
@joelday I know. I'm on it right now at my job as we well need it anyways (a SignalR <> socket.io proxy). At the moment I am focusing on websockets only, dissecting the code to find out what is actually necessary. If nobody at my company is against it (which I doubt tbh), I will release it as soon as there's _something_ working available. At that point anyone is invited to participate, of course. Will post here when that happens.

**Comment by moozzyk** [comment]
@JimPanic - I wrote [this](https://blog.3d-logic.com/2015/03/29/signalr-on-the-wire-an-informal-description-of-the-signalr-protocol/) post after I wrote the C++ client. You might find it useful.

**Comment by JimPanic** [comment]
@moozzyk Amazing, this is very helpful. Thank you!

**Comment by nojaf** [comment]
Any plans to use ES6 modules?
