### ISSUE TITLE
Do we have the code in this repo?

### ISSUE THREAD

**Issue by ghost** [aspnet/SignalR-Client-JS#2]
I wanted to see and learn how this js client works. But I am not able to see any code here. Is it something related to my access levels?

**Comment by Eilon** [comment]
@hanu412 we haven't yet migrated all the SignalR source code from the https://github.com/SignalR organization. You can still find all the JS source code there:
- JavaScript sources: https://github.com/SignalR/SignalR/tree/master/src/Microsoft.AspNet.SignalR.Client.JS
- Bower package: https://github.com/SignalR/bower-signalr

**Comment by JimPanic** [comment]
You could put that into the README. A closed issue that only shows when you actively look for it might be a bit harder to find than two links in the README that doesn't say anything about the sources or the bower package.
